### ISSUE TITLE
old 哥，装不上

### ISSUE THREAD

**Issue by yuerdev** [demones/xlsx-node#1]
![qq20170607-152333](https://user-images.githubusercontent.com/21173134/26866781-515be0a8-4b95-11e7-9a1b-e5d100fc5603.png)
是不是不支持mac啊

**Comment by yuerdev** [comment]
windows也不行，姿势不对啊

**Comment by hopefuture** [comment]
我好久没有维护这个 npm 包了，之前在 mac 上是可以的，你也可以 git clone  然后升级一下 npm 依赖包
试试，有空我会试着更新该组件的，抱歉
